name: come_share
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^0.1.3
  path_provider: ^1.6.11 #keep it low
  path: ^1.6.2
  crypto: ^2.0.6
  provider: ^3.0.0
  sembast: ^2.3.0
  pedantic: ^1.0.0
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  json_annotation: ^3.0.1
  rc_router: ^0.1.0
  url_launcher: ^5.0.2
  intent: ^1.1.0
  share: ^0.6.2
  file_picker: ^1.3.8
  permission_handler: ^3.2.2
  charts_flutter: ^0.9.0
  device_info: ^0.4.1+1
  flutter_barcode_scanner: ^0.1.7
  date_range_picker: ^1.0.5
  csv: ^4.0.3
  flutter_markdown: ^0.3.3
  connectivity: ^0.4.8+6
  uuid: 2.0.4
  collection: ^1.14.11
  equatable: ^1.1.0
  flutter_share: ^1.0.2+1
  gradient_text: ^1.0.2
  flutter_screenutil: ^1.0.2
  #flutter_svg: ^0.17.3+1
  package_info: ^0.4.0+16
  spreadsheet_decoder: ^1.1.0
  flare_flutter: ^2.0.4
  sembast_web: ^1.1.0+1

  #audioplayer: ^0.7.0  # buggy as f*
  #printing: any
  #blue_thermal_printer: ^1.0.8 #DO_NOT upgrade
  #contacts_service: ^0.3.0
  #toast: ^0.1.5
  #youtube_player_flutter: ^6.0.3+2
  #audioplayers: ^0.15.0
  #assets_audio_player: ^2.0.5+6
  #badges: ^1.1.0
  #flutter_sms: 2.0.0+2
  #sms: ^0.2.0
  #firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1
  json_serializable: ^3.1.0
  #flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/svg/calculator.svg
    - assets/collecte.xlsx
    - assets/ksde_qr.png
    - assets/rive/cow.flr
    - assets/no_network.flr
    - assets/photos/milk-logo.png
    - assets/photos/ldb_logo.png
    - assets/photos/biker.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
